### ISSUE TITLE
LINE_MODE crashes my pc

### ISSUE THREAD

**Issue by kelashry** [wg-perception/linemod#34]
HI All

I am trying the object detection library for the first 
I went through the tutorial and managed to get the tabletop example to work with freenect and kinect 1,  currently when I run the Linemode detection after the training , my pc slows down till it becomes unresponsive without any errors in the terminal
I was wondering if anyone have faced this problem before

I am using the Ubuntu 14.04.5 with ROS indigo
Cheers
Khaled

**Comment by JimmyDaSilva** [comment]
@kelashry , it might be the same problem I had a while ago, related to mesa/glut
Check https://github.com/wg-perception/ork_renderer/pull/9 and my post on Feb 26

Good luck!
