### ISSUE TITLE
Linemod training works but it is not detecting coke can

### ISSUE THREAD

**Issue by srinimd2005** [wg-perception/linemod#36]
When ever i run the linemod detection I get this 

Reading the mesh file original.obj
Info,  T0: Load ���W�.obj
Info,  T0: Found a matching importer for this file format
Info,  T0: Import root directory is './'
Error, T0: OBJ: Unable to locate material file ./coke.obj.mtl
Error, T0: OBJ: failed to locate material material_0, skipping
Error, T0: OBJ: failed to locate material material_1, skipping
Error, T0: OBJ: failed to locate material material_2, skipping
Info,  T0: Entering post processing pipeline
Info,  T0: Points: 0, Lines: 0, Triangles: 3, Polygons: 0 (Meshes, X = removed)
Info,  T0: CalcTangentsProcess finished. Tangents have been calculated
Info,  T0: JoinVerticesProcess finished | Verts in: 1536 out: 478 | ~68.9%
Info,  T0: Cache relevant are 3 meshes (512 faces). Average output ACMR is 1.005859
Info,  T0: Leaving post processing pipeline
Loaded 539d95f3026597a4f48fe9bfd50009ff with the number of samples 4579

[ INFO] [1481820107.500078438]: publishing to topic:/recognized_object_array

but it never detects a coke can on my desk. I am using Kinect v2 and iai kinect bridge. Can anyone please help me.

**Comment by JimmyDaSilva** [comment]
For now, I think that if you want to use textures (like the coke.obj) you need to go to the folder with the materials in.
Try `roscd object_recognition_tutorials/data` and run linemod again from there to see if the error persists.

**Comment by srinimd2005** [comment]
Thank you it started detecting. The problem was with kinect calibration.
Is there any solution to use object recognition capture by remapping to kinect v2 rostopics.

**Comment by srinimd2005** [comment]
Hi JimmyDaSilva,

I am having a problem of pose deviation error. I there any possible way to correct the error.

**Comment by JimmyDaSilva** [comment]
@srinimd2005 , I managed to make it work a few months ago. Check this:
https://github.com/wg-perception/linemod/issues/28
