### ISSUE TITLE
Training objects not working

### ISSUE THREAD

**Issue by awesomebytes** [wg-perception/linemod#6]
~/ork/src/ork_linemod/conf$ rosrun object_recognition_core training -c training.ork
Training 6 objects.
computing object_id: 8b8ec44926f9fec2c30d2c54b906ac40
Info,  T0: Load 
Error, T0: Unable to open file "".
Segmentation fault (core dumped)

I get this error when I try to train.

Then obviously if I try to detect objects I get:
No models found for method "LINEMOD"

**Comment by albertodesouza** [comment]
Hi,

I am trying to train a linemod ORK detector but I am observing this error:
 $ rosrun object_recognition_core detection -c `rospack find object_recognition_linemod`/conf/training.ork
 python: /tmp/buildd/ros-hydro-ecto-0.6.7-0precise-20141111-2221/src/lib/scheduler.cpp:326: void ecto::scheduler::compute_stack(): Assertion `! stack_.empty()' failed.
 Aborted (core dumped)

I have tried both instalation modes, from ros repositories and build from source. Both show the same error... Can you help? I would appreciate any suggestion you can offer.

Alberto.

**Comment by albertodesouza** [comment]
Hi,

I just found the reason for the error above. In this tutorial page (that I was following): http://wg-perception.github.io/ork_tutorials/tutorial03/tutorial.html#training

the line:
rosrun object_recognition_core detection -c  `rospack find object_recognition_linemod`/conf/detection.ros.ork`

should be:
rosrun object_recognition_core training -c  `rospack find object_recognition_linemod`/conf/detection.ros.ork
instead.

Cheers,

Alberto.

**Comment by hris2003** [comment]
Hi,

I think the right line should be:

rosrun object_recognition_core training -c `rospack find
object_recognition_linemod/conf/training.ork`

You can make a pull request to suggest a correction to
https://github.com/wg-perception/ork_tutorials.

Cheers,

Ha.

**Comment by vrabaud** [comment]
Hi, I fixed the doc. The code for linemod is about to receive a major improvement/bugfix with #7  so I am closing this one.
